project24/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='auth')),
    path('userhome/', include('userhome.urls', namespace='home')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userhome/urls.py
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('video_player/<str:title>', views.video_page_function, name='video_page'),
]

templates/ush/video.html
{%extends 'theme.html'%}

{%block content%}

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="#">
        Filmstream
    </a>
</nav>
{%if messages%}
{%for m in messages%}
<div class='alert alert-success' role='alert'>{{m}}<button type='button' class='close' data-dismiss='alert'
        aria-label='Close'><span aria-hidden='true'>&times;</span></button></div>
{%endfor%}
{%endif%}
{%load static%}
<!-- carousel -->



<!-- horizontal scroll -->
<div class="container-fluid" id="#cards" style="margin:0px;padding:2.5px;">
    <h5> Latest releases-</h5>
    <div class="horizontalbox">
        {%for film in films%}
        <div class="card-1">
            <a href="{%url 'home:video_page' film.title%}">
                <img class="d-block w-100 h-100" style="object-fit: cover;" src='{{film.thumbnail.url}}'>
            </a>
        </div>
        {%endfor%}
    </div>
</div>



<br>
<hr>
{% load tags %}
<div class="container">
<h1>Your History-</h1>
<ol type="1">
{%for title in history%}
<h3><li>{%remove_uderscore title%}</li></h3>
{%endfor%}
</ol>
</div>



<script>
    function autoRefreshPage()
    {
        window.location = window.location.href;
    }
    setInterval('autoRefreshPage()', 10000);
</script>
{%endblock%}

templates/ush/videopage.html
{%extends 'theme.html'%}


{%block content%}
<br>
<div class="container" id="videobox">
    <h1 align="left">{{video.title}}</h1>
    <video width="100%" controls poster="{{video.thumbnail.url}}">
        <source src="{{ video.videofile.url }}" type='video/mp4'>
    </video>
    <h6 align="left">{{video.rating}}</h6>
    <hr>
    <p style="text-align: left;">{{video.description}}</p>
</div>
<hr>
<br>
<a href="{%url 'home:index'%}">Back</a>
{% endblock %}